# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorNote',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('operator_name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='operator_op_order_i_01779f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorQueue',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('assigned_operator', models.CharField(db_index=True, max_length=200)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending_payment', 'pending_payment'), ('payment_confirmed', 'payment_confirmed'), ('processing', 'processing'), ('awaiting_seller', 'awaiting_seller'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='processing', max_length=30)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('action_required', models.TextField(blank=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['assigned_operator', '-priority', '-updated_at'], name='operator_op_assigne_05a7c5_idx'), models.Index(fields=['status'], name='operator_op_status_148ac3_idx')],
                'unique_together': {('order_id', 'assigned_operator')},
            },
        ),
    ]
