# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FizboOrder',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('service_tier', models.CharField(choices=[('standard', 'DocComplete Standard'), ('premium', 'DocComplete Premium'), ('express', 'DocExpress'), ('heritage', 'DocComplete Heritage')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending_payment', 'pending_payment'), ('payment_confirmed', 'payment_confirmed'), ('processing', 'processing'), ('awaiting_seller', 'awaiting_seller'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='draft', max_length=30)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_operator', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['seller_email', '-created_at'], name='docready_fi_seller__60b5e0_idx'), models.Index(fields=['status', '-updated_at'], name='docready_fi_status_00141a_idx'), models.Index(fields=['assigned_operator'], name='docready_fi_assigne_057cfe_idx')],
            },
        ),
    ]
