# Generated by Django 6.0.3 on 2026-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docready', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizboorder',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
