# Generated by Django 6.0.3 on 2026-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docready', '0002_fizboorder_whatsapp_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizboorder',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
