# Generated by Django 6.0.3 on 2026-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docready', '0003_fizboorder_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizboorder',
            name='service_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('express', 'DocExpress'), ('heritage', 'DocComplete Heritage')], max_length=50),
        ),
    ]
