# Generated by Django 6.0.3 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_updated_at_alter_user_is_active_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('agent', 'Agent'), ('lawyer', 'Lawyer'), ('admin', 'Admin')], default='seller', max_length=20),
        ),
    ]
