# Generated by Django 6.0.3 on 2026-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
