# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('document_type', models.CharField(choices=[('caderneta', 'Caderneta Predial Urbana'), ('certidao', 'Certidão Permanente do Registo Predial'), ('licenca', 'Licença de Utilização'), ('ipt', 'Imposto sobre Propriedade Imóvel (IPT)'), ('energy_cert', 'Energy Certificate (RECS)')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('uploaded', 'uploaded'), ('verified', 'verified'), ('complete', 'complete'), ('expired', 'expired'), ('error', 'error')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size_bytes', models.IntegerField(null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['seller_email', '-updated_at'], name='documents_d_seller__f06bc1_idx'), models.Index(fields=['order_id', 'status'], name='documents_d_order_i_f57dbe_idx'), models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx')],
                'unique_together': {('order_id', 'document_type')},
            },
        ),
    ]
