# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMAReport',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('property_address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_range_min', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_range_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('comparables', models.JSONField(default=list)),
                ('market_analysis', models.JSONField(default=dict)),
                ('report_pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id'], name='smartcma_cm_order_i_2c2b9b_idx'), models.Index(fields=['seller_email'], name='smartcma_cm_seller__b2d829_idx')],
            },
        ),
    ]
