# Generated by Django 5.0.3 on 2026-03-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('provider_case_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('rezerva_reference_id', models.CharField(max_length=64, unique=True)),
                ('callback_url', models.URLField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='created', max_length=20)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(max_length=32)),
                ('upload_token', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('payload_json', models.JSONField()),
                ('delivery_status', models.CharField(default='pending', max_length=32)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='cases.verificationcase')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing'), ('needs_resolution', 'Needs Resolution')], default='missing', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.verificationcase')),
            ],
            options={
                'unique_together': {('provider_case', 'document_key')},
            },
        ),
    ]
