# Generated by Django 6.0.3 on 2026-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentValidity',
            fields=[
                ('document_key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('validity_months', models.IntegerField(blank=True, null=True)),
                ('cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Document Validities',
            },
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='extracted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
    ]
