# Generated by Django 6.0.3 on 2026-03-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_documentvalidity_verificationdocument_expiry_date_and_more'),
        ('cases', '0003_add_document_type_detection'),
    ]

    operations = [
    ]
