# Generated by Django 6.0.3 on 2026-03-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocCheckSession',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('property_type', models.CharField(max_length=50)),
                ('property_location', models.CharField(max_length=100)),
                ('is_mortgaged', models.BooleanField(default=False)),
                ('is_inherited', models.BooleanField(default=False)),
                ('seller_persona', models.CharField(choices=[('urban_resident', 'Urban Resident'), ('non_resident', 'Non-Resident'), ('heir', 'Heir / Inherited'), ('divorce', 'Divorce / Urgent'), ('rural', 'Rural / Legacy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'DocCheck Session',
                'verbose_name_plural': 'DocCheck Sessions',
                'indexes': [models.Index(fields=['email', '-created_at'], name='doccheck_do_email_88ba70_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_documents', models.JSONField(default=list)),
                ('required_tier', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='doccheck.docchecksession')),
            ],
            options={
                'verbose_name': 'DocCheck Result',
            },
        ),
    ]
