# Generated by Django 6.0.3 on 2026-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchecksession',
            name='is_portugal_resident',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='docchecksession',
            name='ownership_type',
            field=models.CharField(choices=[('sole', 'Sole Owner'), ('joint', 'Joint Ownership'), ('inherited', 'Inherited'), ('multiple_heirs', 'Multiple Heirs'), ('other', 'Other')], default='sole', max_length=50),
        ),
        migrations.AddField(
            model_name='docchecksession',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal Timeline'), ('urgent', 'Urgent (30 days)'), ('very_urgent', 'Very Urgent (2 weeks)')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='docchecksession',
            name='seller_persona',
            field=models.CharField(blank=True, choices=[('urban_resident', 'Urban Resident'), ('non_resident', 'Non-Resident'), ('heir', 'Heir / Inherited'), ('divorce', 'Divorce / Urgent'), ('rural', 'Rural / Legacy')], max_length=50, null=True),
        ),
    ]
