# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default='uuid', max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('stripe_checkout_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('service_tier', models.CharField(choices=[('standard', 'DocComplete Standard'), ('premium', 'DocComplete Premium'), ('express', 'DocExpress'), ('heritage', 'DocComplete Heritage')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('refunded', 'refunded')], default='pending', max_length=20)),
                ('refunded_amount_cents', models.IntegerField(default=0)),
                ('reason_for_refund', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='payments_pa_order_i_288dd3_idx'), models.Index(fields=['seller_email', 'status'], name='payments_pa_seller__2dbe2c_idx')],
            },
        ),
    ]
